# Generated by Django 5.2.8 on 2025-11-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Vytilla', 'Vytilla'), ('High Court', 'High Court'), ('Vypin', 'Vypin'), ('Kakkanad', 'Kakkanad'), ('South Chittoor', 'South Chittoor'), ('Cheranalloor', 'Cheranalloor'), ('Eloor', 'Eloor'), ('Fort Kochi', 'Fort Kochi'), ('Willingdon Island', 'Willingdon Island'), ('Mattancherry', 'Mattancherry')], max_length=50)),
                ('destination', models.CharField(choices=[('Vytilla', 'Vytilla'), ('High Court', 'High Court'), ('Vypin', 'Vypin'), ('Kakkanad', 'Kakkanad'), ('South Chittoor', 'South Chittoor'), ('Cheranalloor', 'Cheranalloor'), ('Eloor', 'Eloor'), ('Fort Kochi', 'Fort Kochi'), ('Willingdon Island', 'Willingdon Island'), ('Mattancherry', 'Mattancherry')], max_length=50)),
                ('journey_date', models.DateField()),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_phone', models.CharField(max_length=20)),
                ('no_of_tickets', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
