# Generated by Django 5.2.8 on 2025-11-12 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('position', models.IntegerField()),
                ('capacity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('required_exposure_hours', models.IntegerField(default=0)),
                ('achieved_hours', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InductionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ranked_list', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True)),
                ('cars', models.IntegerField(default=4)),
                ('last_mileage', models.IntegerField(default=0)),
                ('cumulative_mileage', models.IntegerField(default=0)),
                ('status', models.CharField(default='idle', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('branding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.branding')),
                ('stabling_bay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.bay')),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximo_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('trainset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcards', to='depot.trainset')),
            ],
        ),
        migrations.CreateModel(
            name='FitnessCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=64)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('doc', models.CharField(blank=True, max_length=255)),
                ('trainset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certs', to='depot.trainset')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depot.bay')),
                ('assigned_trainset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot.trainset')),
            ],
        ),
    ]
