# Generated by Django 5.2.8 on 2025-11-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='description',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='maximo_id',
        ),

        # 💚 FIXED: assigned_task now has a valid non-null default
        migrations.AddField(
            model_name='jobcard',
            name='assigned_task',
            field=models.CharField(default="Not Provided", max_length=255),
        ),

        # 💚 jobcard_id default is valid
        migrations.AddField(
            model_name='jobcard',
            name='jobcard_id',
            field=models.CharField(default="UNKNOWN", max_length=50),
        ),

        migrations.AddField(
            model_name='jobcard',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),

        # 💚 operator valid default
        migrations.AddField(
            model_name='jobcard',
            name='operator',
            field=models.CharField(default="Unknown", max_length=100),
        ),

        # 💚 status stays non-nullable BUT safe
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
