# Generated by Django 5.2.8 on 2025-11-14 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0002_rename_description_jobcard_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainset',
            name='train_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='assigned_task',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='jobcard_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='operator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mileage', models.IntegerField(default=0)),
                ('cumulative_mileage', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('trainset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileages', to='depot.trainset')),
            ],
        ),
    ]
